In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.set(style="ticks")

Использование класса CountVectorizer

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(encoding='utf-8')

## Векторизация текста на основе модели "мешка слов"

In [4]:
data = pd.read_csv('tags2.csv')
data.head()

name  \
0  Брать, давать и наслаждаться. Как оставаться в...   
1  Роман с самим собой. Как уравновесить внутренн...   
2                    Думай медленно... решай быстро    
3  НИ СЫ. Будь уверен в своих силах и не позволяй...   
4  Психотрюки. 69 приемов в общении, которым не у...   

                                                tags  
0  чувствова себ полн силвстава кажд утр с тот но...  
1  когд ты себ люб ты точн знат что хотет и идт к...  
2  этот книг полност измен ваш жизн вед реч в он ...  
3  книг полн грубоват и прикольн совет по работ н...  
4  психотрюк эт прост при котор помога постав хам...

Подсчет количество слов словаря, входящих в текст


In [5]:
cv.fit(data['tags'])
corpusVocab = cv.vocabulary_
print('Количество сформированных признаков - {}'.format(len(corpusVocab)))

Количество сформированных признаков - 11273


In [6]:
for i in list(corpusVocab)[1:10]:
    print('{}={}'.format(i, corpusVocab[i]))

себ=8683
полн=6813
силвстава=8791
кажд=3261
утр=10362
тот=9881
ног=5389
испытыва=3194
воодушевлен=1172


In [7]:
vectors = cv.fit_transform(data['tags'].values.astype('U'))

In [8]:
vectors

<1627x11273 sparse matrix of type '<class 'numpy.int64'>'
	with 138064 stored elements in Compressed Sparse Row format>

In [9]:
vectors.shape

(1627, 11273)

In [10]:
vectors.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])

In [11]:
# Непустые значения нулевой строки
[i for i in vectors.todense()[0].getA1() if i>0][0:10]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [12]:
cv.get_feature_names_out()[5167:5187]

array(['неполн', 'неполноцен', 'непомерн', 'непониман', 'непонятн',
       'непоправим', 'непосильн', 'непоследовательн', 'непослушан',
       'непосредствен', 'непостижим', 'непочат', 'неправд',
       'неправдоподобн', 'неправильн', 'непревзойден', 'непредвзят',
       'непредвиден', 'непредсказуем', 'непреклон'], dtype=object)

### CountVectorizer - spacy

In [3]:
data = pd.read_csv('spacylem.csv')
data.head()

name  \
0  Брать, давать и наслаждаться. Как оставаться в...   
1  Роман с самим собой. Как уравновесить внутренн...   
2                    Думай медленно... решай быстро    
3  НИ СЫ. Будь уверен в своих силах и не позволяй...   
4  Психотрюки. 69 приемов в общении, которым не у...   

                                                tags  
0  чувствова полн силвстава кажд утр тот ног испы...  
1  люб точн знат хотет идт эт избав негативн шум ...  
2  этот книг полност измен ваш жизн реч нерациона...  
3  книг полн грубоват прикольн совет работ сво об...  
4  психотрюк эт прост при котор помога постав хам...

In [4]:
cv.fit(data['tags'])
corpusVocab = cv.vocabulary_
print('Количество сформированных признаков - {}'.format(len(corpusVocab)))

Количество сформированных признаков - 11688


In [5]:
for i in list(corpusVocab)[1:10]:
    print('{}={}'.format(i, corpusVocab[i]))

полн=7039
силвстава=9126
кажд=3373
утр=10762
тот=10257
ног=5556
испытыва=3305
воодушевлен=1198
приступ=7693


In [6]:
vectors = cv.fit_transform(data['tags'].values.astype('U'))


In [8]:
vectors

array([1, 1, 1, ..., 1, 1, 1])

In [16]:
vectors = cv.fit_transform(data['tags'].values.astype('U'))
# Непустые значения нулевой строки
[i for i in vectors.todense()[0].getA1() if i>0][0:10]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [17]:
vectors.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [18]:
vectors.shape

(1627, 11688)

In [19]:
cv.get_feature_names()[5167:5187]

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['недостижим',
 'недостоверн',
 'недостойн',
 'недоступн',
 'недосыпан',
 'недосяга',
 'недочет',
 'недруг',
 'недуг',
 'нее',
 'нежел',
 'нежела',
 'нежелательн',
 'нежн',
 'нежност',
 'незабыва',
 'независим',
 'независимымиэт',
 'незаконнорожден',
 'незакончен']

In [20]:
from sklearn.metrics.pairwise import cosine_similarity

In [21]:
%%time
similarity = cosine_similarity(vectors)

CPU times: user 144 ms, sys: 29.4 ms, total: 174 ms
Wall time: 178 ms


In [22]:
similarity

array([[1.        , 0.30515686, 0.06555126, ..., 0.18699848, 0.08613361,
        0.13437656],
       [0.30515686, 1.        , 0.13018891, ..., 0.16037325, 0.16329099,
        0.26202789],
       [0.06555126, 0.13018891, 1.        , ..., 0.03626321, 0.06681298,
        0.10423455],
       ...,
       [0.18699848, 0.16037325, 0.03626321, ..., 1.        , 0.09529889,
        0.13380773],
       [0.08613361, 0.16329099, 0.06681298, ..., 0.09529889, 1.        ,
        0.13353894],
       [0.13437656, 0.26202789, 0.10423455, ..., 0.13380773, 0.13353894,
        1.        ]])

In [23]:
similarity.shape

(1627, 1627)

In [24]:
type(similarity)

numpy.ndarray

In [25]:
list(enumerate(similarity[0]))[:10]

[(0, 0.9999999999999993),
 (1, 0.3051568575624323),
 (2, 0.06555126429123272),
 (3, 0.10956204283050466),
 (4, 0.09954037839433628),
 (5, 0.11302717957307888),
 (6, 0.10749309506252303),
 (7, 0.10230576003327752),
 (8, 0.05845116625852977),
 (9, 0.15025941432062115)]

In [26]:
sorted(similarity[0],reverse=True)[:10]

[0.9999999999999993,
 0.3051568575624323,
 0.296898768411412,
 0.2784990134239222,
 0.2655106250581686,
 0.2640422501403042,
 0.2637427126075309,
 0.2623972997045196,
 0.2601648232653073,
 0.25792274980934754]

## Рекомендации

In [27]:
def recommend(rusbook):
    rusbook_index = data[data['name'] == rusbook].index[0]
    distances = similarity[rusbook_index]
    rusbook_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:11]

    for i in rusbook_list:
       print(data.name[data.iloc[i[0]].name])

In [28]:
recommend('Подсознание может все! ')

Я - победитель! 
Go-Giver. Отдавай, чтобы получать 
Деньги, успех и вы 
Счастье для чайников 
Счастье без ошибок 
Мышление наоборот. Каждый - гениален 
Азбука умственного труда. Как организовать свой труд и отдых, как пользоваться своею памятью, как читать, как слушать 
Как завоевывать друзей и оказывать влияние на людей в эпоху цифровых технологий 
Думай и богатей по-русски 
Как стать законченным неудачником в жизни, работе и во всем остальном. 44 1/2 шага к стойкой неполноценности / (2 изд). Макдермотт С. (Олимп-Бизнес) 


In [29]:
recommend('ЛЮБИ СЕБЯ. Словно от этого зависит твоя жизнь ')

Бизнес-ведьмы. О внутренней силе, мудрости и смелости выбирать свою тропу 
Жизнь - игра. Правила победителей + Жизнь, полная любви. Часть 1. Посланник. Часть 2. Постыдная тайна + Жизнь. Любовь. Смех. Превращая жизнь в праздник (комплект из 3-х книг в упаковке) 
Жизнь в плюсе. Принципы построения счастливой жизни. Почему нет? (комплект из 3 книг) 
Глазами любви. Как запустить свой новый счастливый сценарий. Дневник-тренинг 
Без фильтров. Истории, которые делают нас живыми 
Жизнь просто Бизнес 
Почему нет? Вдохновение для жизни без "если" и "но" 
Я отключился от Интернета. Как выжить без Интернета после передозировки 
Просто счастье. Метафорические карты 
О жизни 


In [30]:
recommend('Депрессия и выгорание. Как понять истинные причины плохого настроения и избавиться от них ')

Прививка от стресса. Как стать хозяином своей жизни 
Сила намерения. Как реализовать свои мечты и желания 
дневник диалектической поведенческой терапии 
Возлюби болезнь свою. Как стать здоровым, познав радость жизни 
Просто делай! Делай просто! Видеокнига + Делай! Ежедневник №1 (комплект) 
Начни с чистого листа! 2 книги, которые помогут превратить мечту в жизнь (Комплект из 2 книг) 
Паркуйся правильно, и еще 32 принципа яркой жизни 
Комплект. Идеальный подарок "Будь счастлива!" 3 книги, которые помогут полюбить и принять себя (Идеальных не бывает + Вместе или врозь + Tell me more) 
Духовный воин 4. Победа над врагами ума 
Практический курс доктора Синельникова. Как научиться любить себя 


In [31]:
data = pd.read_csv('dataclean.csv')
data

name            author  \
0     Брать, давать и наслаждаться. Как оставаться в...  Татьяна Мужицкая   
1     Роман с самим собой. Как уравновесить внутренн...  Татьяна Мужицкая   
2                       Думай медленно... решай быстро    Даниэль Канеман   
3     НИ СЫ. Будь уверен в своих силах и не позволяй...      Джен Синсеро   
4     Психотрюки. 69 приемов в общении, которым не у...       Игорь Рызов   
...                                                 ...               ...   
1622    Счастливая жизнь без панических атак и страхов                NaN   
1623                 Думай и богатей в годы безденежья                NaN   
1624  Близко к сердцу. Как жить, если вы слишком чув...           Санд И.   
1625  Занимательная кинесика, или Тайны жестов, поз,...               NaN   
1626  Наслаждение от каждого дня. Доступная всем про...               NaN   

                             section               publish    age    year  \
0     Саморазвитие и личностный рост                   NaN   16+   2022.0   
1     Саморазвитие и личностный рост                   NaN   16+   2022.0   
2              Популярная психология                   АСТ   16+   2022.0   
3     Саморазвитие и личностный рост                   NaN   16+   2022.0   
4     Саморазвитие и личностный рост                   NaN   12+   2022.0   
...                              ...                   ...    ...     ...   
1622  Саморазвитие и личностный рост  Издательские решения   16+   2016.0   
1623  Саморазвитие и личностный рост                   NaN   16+   2018.0   
1624  Саморазвитие и личностный рост               Альпина    NaN  2016.0   
1625  Саморазвитие и личностный рост              Прометей    NaN  2022.0   
1626  Саморазвитие и личностный рост                   NaN   16+   2022.0   

      pages rating                                               cove  \
0     256.0     5   https://ndc.book24.ru/resize/410x590/iblock/3d...   
1     304.0     5   https:https://cdn.book24.ru/v2/ITD000000001044...   
2     656.0   4,6   https://ndc.book24.ru/resize/410x590/iblock/0a...   
3     320.0   4,2   https://ndc.book24.ru/resize/410x590/iblock/54...   
4     256.0     5   https://ndc.book24.ru/resize/410x590/iblock/74...   
...     ...    ...                                                ...   
1622  120.0   0,0   https://ndc.book24.ru/resize/410x590/iblock/28...   
1623  192.0   0,0   https://ndc.book24.ru/resize/410x590/iblock/fe...   
1624  158.0   0,0   https://ndc.book24.ru/resize/410x590/iblock/fe...   
1625  480.0   0,0   https://ndc.book24.ru/resize/410x590/iblock/4c...   
1626  240.0   0,0   https://ndc.book24.ru/resize/410x590/iblock/18...   

                                            description  
0     Чувствовать себя полным сил. Вставать каждое у...  
1     Когда ты себя любишь, ты точно знаешь, чего хо...  
2     Эта книга полностью изменит вашу жизнь: ведь р...  
3     Книга полна грубоватых и прикольных советов по...  
4     Психотрюки — это простые приемы, которые помог...  
...                                                 ...  
1622  Хронический стресс, тревога, приступы паники, ...  
1623  Годы экономического спада в стране "подкосили"...  
1624  Высокочувствительные люди, или «новые интровер...  
1625  Кинесика — это молчаливый язык, язык тела, с п...  
1626  Жизнь кажется пресной и безвкусной?Все краски ...  

[1627 rows x 10 columns]

In [32]:
import pickle

In [33]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [34]:
pickle.dump(data.to_dict(),open('books_dict.pkl','wb'))