In [1]:
import pandas as pd
import seaborn as sns
%matplotlib inline
sns.set(style="ticks")

Использование класса CountVectorizer

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
count_vectorizer = CountVectorizer(encoding='utf-8')

## Векторизация текста на основе модели "мешка слов"

In [3]:
data = pd.read_csv('tags2.csv')
data.head()

name  \
0  Брать, давать и наслаждаться. Как оставаться в...   
1  Роман с самим собой. Как уравновесить внутренн...   
2                    Думай медленно... решай быстро    
3  НИ СЫ. Будь уверен в своих силах и не позволяй...   
4  Психотрюки. 69 приемов в общении, которым не у...   

                                                tags  
0  чувствова себ полн силвстава кажд утр с тот но...  
1  когд ты себ люб ты точн знат что хотет и идт к...  
2  этот книг полност измен ваш жизн вед реч в он ...  
3  книг полн грубоват и прикольн совет по работ н...  
4  психотрюк эт прост при котор помога постав хам...

Подсчет количество слов словаря, входящих в текст


In [4]:
count_vectorizer.fit(data['tags'])
corpusVocab = count_vectorizer.vocabulary_
print('Количество сформированных признаков - {}'.format(len(corpusVocab)))

Количество сформированных признаков - 11908


In [5]:
for i in list(corpusVocab)[1:10]:
    print('{}={}'.format(i, corpusVocab[i]))

себ=9152
полн=7154
силвстава=9266
кажд=3440
утр=10947
тот=10435
ног=5669
испытыва=3370
воодушевлен=1229


In [6]:
vectors = count_vectorizer.fit_transform(data['tags'].values.astype('U'))

In [7]:
vectors

<1618x11908 sparse matrix of type '<class 'numpy.int64'>'
	with 136419 stored elements in Compressed Sparse Row format>

In [8]:
vectors.shape

(1618, 11908)

In [9]:
vectors.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])

In [10]:
# Непустые значения нулевой строки
[i for i in vectors.todense()[0].getA1() if i>0][0:10]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [11]:
count_vectorizer.get_feature_names_out()[5167:5187]

array(['находилисьмарин', 'находк', 'находчив', 'нахожден', 'нац',
       'нацел', 'нацелива', 'наценк', 'национальн', 'нацистск', 'нача',
       'началосаморазвит', 'начальн', 'начальник', 'начальникомбо',
       'начальств', 'начальстваденегпогодысупругаправительств',
       'начатьсаморазвит', 'начин', 'начина'], dtype=object)

### CountVectorizer - spacy

In [12]:
data = pd.read_csv('spacylem.csv')
data.head()

name  \
0  Брать, давать и наслаждаться. Как оставаться в...   
1  Роман с самим собой. Как уравновесить внутренн...   
2                    Думай медленно... решай быстро    
3  НИ СЫ. Будь уверен в своих силах и не позволяй...   
4  Психотрюки. 69 приемов в общении, которым не у...   

                                                tags  
0  чувствова полн силвстава кажд утр тот ног испы...  
1  люб точн знат хотет идт эт избав негативн шум ...  
2  этот книг полност измен ваш жизн реч нерациона...  
3  книг полн грубоват прикольн совет работ сво об...  
4  психотрюк эт прост при котор помога постав хам...

In [13]:
count_vectorizer.fit(data['tags'])
corpusVocab = count_vectorizer.vocabulary_
print('Количество сформированных признаков - {}'.format(len(corpusVocab)))

Количество сформированных признаков - 12321


In [14]:
for i in list(corpusVocab)[1:10]:
    print('{}={}'.format(i, corpusVocab[i]))

полн=7378
силвстава=9600
кажд=3550
утр=11349
тот=10811
ног=5836
испытыва=3479
воодушевлен=1255
приступ=8078


In [15]:
vectors = count_vectorizer.fit_transform(data['tags'].values.astype('U'))

In [16]:
vectors

<1618x12321 sparse matrix of type '<class 'numpy.int64'>'
	with 113027 stored elements in Compressed Sparse Row format>

In [17]:
vectors = count_vectorizer.fit_transform(data['tags'].values.astype('U'))
# Непустые значения нулевой строки
[i for i in vectors.todense()[0].getA1() if i>0][0:10]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [18]:
vectors.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [19]:
vectors.shape

(1618, 12321)

In [20]:
count_vectorizer.get_feature_names()[5167:5187]

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['намерен',
 'намеренсаморазвитие',
 'намест',
 'намет',
 'намечен',
 'намн',
 'намсаморазвитие',
 'нанаш',
 'нанесен',
 'наниза',
 'нанос',
 'наносн',
 'наоборот',
 'наоборотсаморазвитие',
 'наобум',
 'наодин',
 'наом',
 'нападен',
 'наперегонк',
 'наперед']

In [21]:
from sklearn.metrics.pairwise import cosine_similarity

In [22]:
%%time
similarity = cosine_similarity(vectors)

CPU times: user 211 ms, sys: 50.5 ms, total: 261 ms
Wall time: 270 ms


In [23]:
similarity

array([[1.        , 0.29982264, 0.06634798, ..., 0.18062146, 0.08154101,
        0.12632279],
       [0.29982264, 1.        , 0.13185241, ..., 0.15322618, 0.15320647,
        0.25864676],
       [0.06634798, 0.13185241, 1.        , ..., 0.03673316, 0.06780635,
        0.10942203],
       ...,
       [0.18062146, 0.15322618, 0.03673316, ..., 1.        , 0.09028939,
        0.12433397],
       [0.08154101, 0.15320647, 0.06780635, ..., 0.09028939, 1.        ,
        0.12909944],
       [0.12632279, 0.25864676, 0.10942203, ..., 0.12433397, 0.12909944,
        1.        ]])

In [24]:
similarity.shape

(1618, 1618)

In [25]:
type(similarity)

numpy.ndarray

In [26]:
list(enumerate(similarity[0]))[:10]

[(0, 1.0000000000000009),
 (1, 0.2998226426093877),
 (2, 0.06634797880872434),
 (3, 0.10301081696649858),
 (4, 0.09134420089491038),
 (5, 0.10772843571098123),
 (6, 0.10840110520942302),
 (7, 0.05052911526399114),
 (8, 0.14467423695414222),
 (9, 0.15631647522104605)]

In [27]:
sorted(similarity[0],reverse=True)[:10]

[1.0000000000000009,
 0.2998226426093877,
 0.2964330420312403,
 0.26994113627652894,
 0.2609973475016989,
 0.2592088920543522,
 0.2583514444959201,
 0.25812327876704005,
 0.2502800993230099,
 0.249822632116729]

## Рекомендации

In [28]:
def recommend(book):
    book_index = data[data['name'] == book].index[0]
    distances = similarity[book_index]
    book_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:11]

    for i in book_list:
       print(data.name[data.iloc[i[0]].name])

In [29]:
recommend('Подсознание может все! ')

Go-Giver. Отдавай, чтобы получать 
Я - победитель! 
Счастье без ошибок 
Думай и богатей по-русски 
Счастье для чайников 
99+1 способ быть счастливее каждый день + Ты счастливчик! Вдохновляющий план личностного роста + Записки экономиста о счастье, успехе, процветании (комплект из 3-х книг в упаковке) 
Как завоевывать друзей и оказывать влияние на людей в эпоху цифровых технологий 
Хватит думать! Действуй!. Энтони Р. 
Как стать законченным неудачником в жизни, работе и во всем остальном. 44 1/2 шага к стойкой неполноценности / (2 изд). Макдермотт С. (Олимп-Бизнес) 
Мышление наоборот. Каждый - гениален 


In [30]:
recommend('ЛЮБИ СЕБЯ. Словно от этого зависит твоя жизнь ')

Бизнес-ведьмы. О внутренней силе, мудрости и смелости выбирать свою тропу 
Жизнь в плюсе. Принципы построения счастливой жизни. Почему нет? (комплект из 3 книг) 
Жизнь - игра. Правила победителей + Жизнь, полная любви. Часть 1. Посланник. Часть 2. Постыдная тайна + Жизнь. Любовь. Смех. Превращая жизнь в праздник (комплект из 3-х книг в упаковке) 
Без фильтров. Истории, которые делают нас живыми 
Просто счастье. Метафорические карты 
Почему нет? Вдохновение для жизни без "если" и "но" 
Глазами любви. Как запустить свой новый счастливый сценарий. Дневник-тренинг 
Слушай свое тело. Снова и снова 
Я отключился от Интернета. Как выжить без Интернета после передозировки 
Жизнь просто Бизнес 


In [31]:
recommend('Депрессия и выгорание. Как понять истинные причины плохого настроения и избавиться от них ')

Прививка от стресса. Как стать хозяином своей жизни 
дневник диалектической поведенческой терапии 
Сила намерения. Как реализовать свои мечты и желания 
Возлюби болезнь свою. Как стать здоровым, познав радость жизни 
Практический курс доктора Синельникова. Как научиться любить себя 
Просто делай! Делай просто! Видеокнига + Делай! Ежедневник №1 (комплект) 
Эмоциональное мышление как инструмент достижения успеха 
Нарушение сна. Депрессия. Неврастения. Материальная основа, причины и исцеление 
Боремся со стрессом. Сборник простых и действенных упражнений 
Учимся мыслить позитивно. Сборник простых и действенных упражнений 


In [32]:
data = pd.read_csv('clean_data.csv')
data

name            author  \
0     Брать, давать и наслаждаться. Как оставаться в...  Татьяна Мужицкая   
1     Роман с самим собой. Как уравновесить внутренн...  Татьяна Мужицкая   
2                       Думай медленно... решай быстро    Даниэль Канеман   
3     НИ СЫ. Будь уверен в своих силах и не позволяй...      Джен Синсеро   
4     Психотрюки. 69 приемов в общении, которым не у...       Игорь Рызов   
...                                                 ...               ...   
1613    Счастливая жизнь без панических атак и страхов                NaN   
1614                 Думай и богатей в годы безденежья                NaN   
1615  Близко к сердцу. Как жить, если вы слишком чув...           Санд И.   
1616  Занимательная кинесика, или Тайны жестов, поз,...               NaN   
1617  Наслаждение от каждого дня. Доступная всем про...               NaN   

                             section               publish    age    year  \
0     Саморазвитие и личностный рост                   NaN   16+   2022.0   
1     Саморазвитие и личностный рост                   NaN   16+   2022.0   
2              Популярная психология                   АСТ   16+   2022.0   
3     Саморазвитие и личностный рост                   NaN   16+   2022.0   
4     Саморазвитие и личностный рост                   NaN   12+   2022.0   
...                              ...                   ...    ...     ...   
1613  Саморазвитие и личностный рост  Издательские решения   16+   2016.0   
1614  Саморазвитие и личностный рост                   NaN   16+   2018.0   
1615  Саморазвитие и личностный рост               Альпина    NaN  2016.0   
1616  Саморазвитие и личностный рост              Прометей    NaN  2022.0   
1617  Саморазвитие и личностный рост                   NaN   16+   2022.0   

      pages rating                                               cove  \
0     256.0     5   https://ndc.book24.ru/resize/410x590/iblock/3d...   
1     304.0     5   https:https://cdn.book24.ru/v2/ITD000000001044...   
2     656.0   4,6   https://ndc.book24.ru/resize/410x590/iblock/0a...   
3     320.0   4,2   https://ndc.book24.ru/resize/410x590/iblock/54...   
4     256.0     5   https://ndc.book24.ru/resize/410x590/iblock/74...   
...     ...    ...                                                ...   
1613  120.0   0,0   https://ndc.book24.ru/resize/410x590/iblock/28...   
1614  192.0   0,0   https://ndc.book24.ru/resize/410x590/iblock/fe...   
1615  158.0   0,0   https://ndc.book24.ru/resize/410x590/iblock/fe...   
1616  480.0   0,0   https://ndc.book24.ru/resize/410x590/iblock/4c...   
1617  240.0   0,0   https://ndc.book24.ru/resize/410x590/iblock/18...   

                                            description  
0     Чувствовать себя полным сил. Вставать каждое у...  
1     Когда ты себя любишь, ты точно знаешь, чего хо...  
2     Эта книга полностью изменит вашу жизнь: ведь р...  
3     Книга полна грубоватых и прикольных советов по...  
4     Психотрюки — это простые приемы, которые помог...  
...                                                 ...  
1613  Хронический стресс, тревога, приступы паники, ...  
1614  Годы экономического спада в стране "подкосили"...  
1615  Высокочувствительные люди, или «новые интровер...  
1616  Кинесика — это молчаливый язык, язык тела, с п...  
1617  Жизнь кажется пресной и безвкусной?Все краски ...  

[1618 rows x 10 columns]

In [33]:
import pickle

In [34]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [35]:
pickle.dump(data.to_dict(),open('books_dict.pkl','wb'))